# Generated by Django 2.2 on 2020-07-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='deposit_by',
            field=models.CharField(choices=[('Bitcoin', 'bitcoin'), ('Bank', 'bank')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
