# Generated by Django 2.2 on 2020-08-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200824_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='select_plan',
            field=models.CharField(choices=[('Mini', 'Mini'), ('Entry', 'entry'), ('Silver', 'silver'), ('Gold', 'gold'), ('Platinum', 'platinum')], default='', max_length=40),
            preserve_default=False,
        ),
    ]
