# Generated by Django 2.2 on 2020-07-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_deposit_deposit_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='currency',
            field=models.CharField(choices=[('USD', 'usd'), ('EUR', 'eur'), ('GBP', 'pounds')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deposit',
            name='deposit_by',
            field=models.CharField(choices=[('Bitcoin', 'bitcoin')], max_length=20),
        ),
    ]
