# Generated by Django 2.2 on 2020-08-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_profile_select_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='select_plan',
            field=models.CharField(choices=[('Mini', 'Mini'), ('Entry', 'Entry'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], max_length=40),
        ),
    ]
