# Generated by Django 2.2 on 2020-07-14 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200714_0652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='currency',
            new_name='select_currency',
        ),
        migrations.RenameField(
            model_name='deposit',
            old_name='deposit_by',
            new_name='select_payment_method',
        ),
    ]
