# Generated by Django 2.2 on 2020-07-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200714_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='select_currency',
            field=models.CharField(choices=[('usd', 'USD'), ('eur', 'EUR'), ('pounds', 'GBP')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/static/images/photo-of-lighthouse.jpg', upload_to='profile_pictures/'),
        ),
    ]
